[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "jupyter>=1.1.1",
    "ruff>=0.11.2",
    "streamlit>=1.43.2",
    "unicorn>=2.1.3",
    "uvicorn>=0.34.0",
]
